# Generated by Django 2.1.5 on 2019-01-24 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_on', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.CharField(choices=[('notebooks', 'Notebooks'), ('eletrodomesticos', 'Eletrodomésticos'), ('moveis', 'Móveis'), ('smartphone', 'Smartphone')], max_length=16)),
            ],
        ),
    ]
